export const INIT = "__INIT__"
export const SET_REPOS = "SET_REPOS"
export const SET_VALUE = "SET_VALUE"
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SET_PAGINATION_RANGE = "SET_PAGINATION_RANGE"